apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentimentapi
  name: sentimentapi
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.sentimentapi.replicaCount }}
  selector:
    matchLabels:
      app: sentimentapi
  template:
    metadata:
      labels:
        app: sentimentapi
    spec:
      containers:
      - image: adammcquistan/textblob-sentiment-api:latest
        name: sentimentapi
        ports:
        - containerPort: {{ .Values.sentimentapi.containerPort }}