apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentimentapi
  name: sentimentapi
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.sentimentapi.containerPort }}
    protocol: {{ .Values.sentimentapi.protocol }}
    targetPort: {{ .Values.sentimentapi.containerPort }}
  selector:
    app: sentimentapi
  type: ClusterIP