version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  nlpapp:
    image: adammcquistan/flask-nlp-app
    container_name: nlpapp
    environment:
      BOOTSTRAP_SERVER: "broker:29092"
      KAFKA_TOPIC: "urls"
      REDIS_HOST: redis
    depends_on:
      - redis
      - broker
      - nlpconsumer
    ports:
      - "5005:5000"

  nlpconsumer:
    image: adammcquistan/nlp-kafka-consumer
    container_name: nlpconsumer
    environment:
      BOOTSTRAP_SERVER: "broker:29092"
      KAFKA_TOPIC: "urls"
      REDIS_HOST: redis
      CONSUMER_GROUP: urls-0
    depends_on:
      - redis
      - broker

  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
