apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: textblob-sentiment-api
  name: textblob-sentiment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: textblob-sentiment-api
  template:
    metadata:
      labels:
        app: textblob-sentiment-api
    spec:
      containers:
      - image: adammcquistan/textblob-sentiment-api:0.2.0
        name: textblob-sentiment-api
        ports:
        - containerPort: 8000
